### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Knucklehead-McSpazatron** [AhmadIbrahiim/Website-downloader#6]
When trying to download any website, you receive this error:
`NotFoundError: Not Found
    at /workspace/Website-downloader/app.js:27:8
    at Layer.handle [as handle_request] (/workspace/Website-downloader/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/workspace/Website-downloader/node_modules/express/lib/router/index.js:317:13)
    at /workspace/Website-downloader/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/workspace/Website-downloader/node_modules/express/lib/router/index.js:335:12)
    at next (/workspace/Website-downloader/node_modules/express/lib/router/index.js:275:10)
    at /workspace/Website-downloader/node_modules/express/lib/router/index.js:635:15
    at next (/workspace/Website-downloader/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/workspace/Website-downloader/node_modules/express/lib/router/index.js:174:3)
    at router (/workspace/Website-downloader/node_modules/express/lib/router/index.js:47:12)`

**Comment by AhmadIbrahiim** [comment]
@Knucklehead-McSpazatron Would you please write more info about the issues? what is your OS?

**Comment by Knucklehead-McSpazatron** [comment]
> @Knucklehead-McSpazatron Would you please write more info about the issues? what is your OS?

I was running online in Gitpod, which is Linux based.
