### ISSUE TITLE
404 Not Found on form submission

### ISSUE THREAD

**Issue by py660** [AhmadIbrahiim/Website-downloader#60]
Public Server:
<img width="362" alt="Screenshot 2023-05-05 at 11 28 34 PM" src="https://user-images.githubusercontent.com/93660666/236596592-2f643409-4af1-4d79-abbc-a8940c3b77cf.png">

Local Server:
<img width="964" alt="Screenshot 2023-05-05 at 11 29 00 PM" src="https://user-images.githubusercontent.com/93660666/236596611-9339a2cc-7065-42da-9f20-9f9e75c5aaa9.png">

**Comment by Nisheet-Patel** [comment]
NotFoundError: Not Found
    at D:\Projects\Website-downloader\app.js:27:8
    at Layer.handle [as handle_request] (D:\Projects\Website-downloader\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:323:13)
    at D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:341:12)
    at next (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:275:10)
    at D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:641:15
    at next (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Projects\Website-downloader\node_modules\express\lib\router\index.js:47:12)
    
    got same error

**Comment by Filaipus** [comment]
Same here. Tried different node versions, making sure it's running as admin, changing the port, etc... no luck.
